bump bundle to support Dropwizard 2.x.x
pac4j/dropwizard-pac4j pull request #51
Opened 2020-03-26 18:27 UTC by richeyh

as 2.x.x has now been released anyone utilizing this bundle is going to need this bump in order to get there application working

2020-03-26 18:27 UTC, richeyh commented on pom.xml
> +  <version>4.0.0-SNAPSHOT</version>
went ahead and bumped a major for this

2020-03-26 19:24 UTC, richeyh commented
looks like a bunch of extraneous warn logging is coming in related to 
MultiException stack 1 of 3
org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=Pac4JValueFactoryProvider$Pac4JProfileValueFactoryProvider,parent=Pac4JValueFactoryProvider$ProfileInjectionResolver,qualifiers={},position=0,optional=false,self=false,unqualified=null,2086477093)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:51)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:205)


after bumping the versions, i can either drop warn logs in the build or a fix will need to be put in upstream it looks like

2020-05-22 18:49 UTC, Naveg commented
Looks like https://github.com/pac4j/jax-rs-pac4j/issues/45 was released. Can we move forward with this one now?

2020-06-21 05:12 UTC, Naveg commented
@leleuj anything I can do to help with this one?

2020-06-22 07:28 UTC, leleuj commented
Sure.

I plan to upgrade the next major versions of `jax-rs-pac4j` and `dropwizard-pac4j` to `pac4j` v4, but it won't be until September/October.

So we could create a version 4.0.0 of `dropwizard-pac4j` based on `jax-rs-pac4j` v3.0.3 and `Dropwizard` v2.
If you can submit a PR to do that (after the appropriate testing), I'll release the v4.0.0 of `dropwizard-pac4j` based on `Dropwizard` v2.

2020-09-10 14:29 UTC, leleuj commented
I just upgraded `dropwizard-pac4j` v4.0.0-SNAPSHOT to pac4j v4, based on `jersey225-pac4j` v4.0.0-SNAPSHOT.
I'll first cut the v4.0.0 releases then we'll upgrade to Dropwizard v2.

2020-09-11 12:07 UTC, leleuj commented
@richeyh Can you update this PR with version 5.0.0-SNAPSHOT for `dropwizard-pac4j` and Dropwizard v2?
Can you open another PR for the demo: https://github.com/pac4j/dropwizard-pac4j-demo? Thanks

2020-12-15 20:43 UTC, richeyh commented
@leleuj pr has been update

2020-12-15 21:43 UTC, richeyh commented
not sure whats going on with the build 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project dropwizard-pac4j: Execution default-resources of goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources failed: Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-resources-plugin:jar:2.6 -> org.apache.maven:maven-plugin-api:jar:2.0.6: Failed to read artifact descriptor for org.apache.maven:maven-plugin-api:jar:2.0.6: Could not transfer artifact org.apache.maven:maven-plugin-api:pom:2.0.6 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]

i didn't touch this so not sure whats wrong with travis trying to download this

2020-12-16 07:35 UTC, leleuj commented
OK. Thanks for the update.

I restarted the build, Travis does not work very well lately.

Is JDK 11 mandatory for Dropwizard v2?

I created a 4.0.x branch and updated the master to v5.0.0-SNAPSHOT. This PR should go on a new major version.

Another PR must be opened for the demo as well: https://github.com/pac4j/dropwizard-pac4j-demo

2020-12-16 15:32 UTC, richeyh commented
yes jdk11 is mandatory, ill try to get some time to rebase this then for the new master branch and get a PR open for that demo application

2020-12-16 15:51 UTC, richeyh commented
PR is open for the demo dependent on this being completed

2020-12-16 16:31 UTC, leleuj requested changes

2020-12-16 16:31 UTC, leleuj commented on pom.xml
>      <maven.compiler.source>1.8</maven.compiler.source>
If JDK 11 is mandatory, this should be changed.

2020-12-16 20:57 UTC, richeyh commented on pom.xml
> -        <artifactId>findbugs-maven-plugin</artifactId>
find bugs is no longer supported and moved to spot bugs for java 11 support

2020-12-17 07:04 UTC, leleuj commented
Thanks for your contribution. Merging

2020-12-17 07:04 UTC, merged